---
title: "SISG 2021 Module 16: Computational Pipeline for WGS Data"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
link-citations: yes
github-repo: UW-GAC/SISG_2021
description: "Course materials for SISG 2021 Module 16"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE, message=FALSE)
```

# Introduction

This site contains course materials for SISG Module 16: Computational Pipeline for WGS Data, July 21-23, 2021.

**Lectures**

Videos and slides for lectures are linked below in the schedule. Links to live sessions can be found at https://si.biostat.washington.edu/suminst/sisg2020/modules/SM2017 (make sure to log in).

**Exercises**

To work through the exercises, log into https://platform.sb.biodatacatalyst.nhlbi.nih.gov with your username and password.

**Slack**

Join the Slack channel here: https://uwbiostatisticssisg.slack.com

**Data**

Data used is located in the [github repository](https://github.com/UW-GAC/SISG_2021) from which the site is built.


## Schedule

NOTE: All times are Pacific Daylight Time (GMT-07:00)

**Wednesday, July 21**

- **Zoom session 11:30-13:15 PDT** - Introduction and Genomic Data Storage
    - **Lecture**
        - Introduction ([video]()) ([slides](https://docs.google.com/presentation/d/17DFvIH97RhcY6gq-BRYsxL-0r2jgl_p1-EMsgGXIYoE/edit?usp=sharing))
        - Using BioData Catalyst for SISG exercises ([pre-recorded video - 11 min](https://washington.zoom.us/rec/share/z_BtN6jw5mVLQqfozUjyVKMtLLjvX6a8g3Qb8_YMnxnMNLbhANUyCVqRIROOytne?startTime=1595869554000))
        - Sequencing data formats ([pre-recorded video - 15 min](https://washington.zoom.us/rec/share/3OZtIZX_7mZLXtLyuB35R7EEJI7GX6a8hiAYrKELyR27RU_39JyIFRL8b5w4UuhF?startTime=1594683337000)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/Sequencing_data_formats_1.pdf))
        - Intro to Genomic Data Storage ([pre-recorded video - 17 min](https://washington.zoom.us/rec/share/ptwyaIrp83xJaZ3Cw3vEaq0sGNjEaaa8hiNN-PUNmU_BnBgez69k4oCz449iOgL4?startTime=1594840618000)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/GDS_intro_2.pdf))
    - **Interactive breakout rooms**
        - GDS format ([Demo](https://uw-gac.github.io/SISG_2021/gds-format.html)) ([Exercise](https://uw-gac.github.io/SISG_2021/gds-format.html#exercises)) ([Solution](https://uw-gac.github.io/SISG_2021/gds-format.html#solutions))
        - Discussion ([video]())
        
- **Zoom session 13:45-14:30 PDT** - Phenotype harmonization
    - **Lecture**
        - Phenotype harmonization ([pre-recorded video - 19 min](https://washington.zoom.us/rec/share/5JV7ILH-1jNIE4Hc2gL1Yq48Br_vaaa8hnIb8_ELyUdlGBoRiHsdmGIpd5zz6kZn?startTime=1595370005000)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/pheno_harmonization.pdf))
    - **Interactive breakout rooms**
        - Harmonization in R ([Demo](https://uw-gac.github.io/SISG_2021/phenotype-harmonization.html)) ([Exercise]()) ([Solution]())
        - Discussion ([video]())

**Thursday, July 22**

- **Zoom session 8:00-9:45 PDT** - Association tests, Part I
    - **Lecture**
        - Association tests: Methods and motivation ([pre-recorded video - 57 min](https://drive.google.com/file/d/1ECge7BRjxzXTFqELaWK0yzcQK7gu8mlC/view?usp=sharing)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/SISG20AssocTests.pdf))
        - GENESIS for association tests ([pre-recorded video - 11 min](https://washington.zoom.us/rec/share/3elQCuvU5jtOZ7fvyFnRaLYsJdu5X6a8g3dK8_YKnh4NQI_41ZS6bU1xORhZMPGO?startTime=1595363212000)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/R_assoc_tests_2.pdf))
    - **Interactive breakout rooms**
        - Null model ([Demo](https://uw-gac.github.io/SISG_2021/association-tests-part-i.html)) ([Exercise](https://uw-gac.github.io/SISG_2021/association-tests-part-i.html#exercise)) ([Solution](https://uw-gac.github.io/SISG_2021/association-tests-part-i.html#solution))
        - Single-variant association tests ([Demo](https://uw-gac.github.io/SISG_2021/association-tests-part-i.html#single-variant-association-tests)) ([Exercise](https://uw-gac.github.io/SISG_2021/association-tests-part-i.html#exercise-1)) ([Solution](https://uw-gac.github.io/SISG_2021/association-tests-part-i.html#solution-1))
        - Discussion ([video]())
        
- **Zoom session 10:15-11:45 PDT** - Association tests, Part II
    - **Lecture**
        - Aggregate tests ([pre-recorded video - 46 min](https://drive.google.com/file/d/1L8JVcijItOwEhYIsVkOALFdeAigL1tTJ/view?usp=sharing)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/SISG20AssocTests.pdf))
    - **Interactive breakout rooms**
        - Sliding window tests ([Demo](https://uw-gac.github.io/SISG_2021/association-tests-part-ii.html)) ([Exercise](https://uw-gac.github.io/SISG_2021/association-tests-part-ii.html#exercise-2)) ([Solution](https://uw-gac.github.io/SISG_2021/association-tests-part-ii.html#solution-2))
        - Discussion ([video]())
        
- **Zoom session 12:45-14:30 PDT** - Population Structure and Relatedness
    - **Lecture**
        - Population structure inference ([pre-recorded video - 33 min](https://drive.google.com/file/d/1hLtTP1b6aUDBbz9mQ2i9J9Yg3Zbfsvvm/view?usp=sharing)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/Population_Structure_Inference_2020.pdf))
        - Relatedness inference ([pre-recorded video - 25 min](https://drive.google.com/file/d/1JMlVvEGU4x9u2UBIJiw7RRIFUrbNdj3f/view?usp=sharing)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/Relatedness_Inference_2020.pdf))
        - R packages for PCA and relatedness ([pre-recorded video - 9 min](https://washington.zoom.us/rec/share/uup8C5Ts50VOWpWdxHDDWvUzE7nieaa8gHVP_qFcxUt1umphrSYNDW9yDt3q5M-n?startTime=1595442394000)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/R_kinship_pca_1.pdf))
    - **Interactive breakout rooms**
        - Ancestry and relatedness inference ([Demo](https://uw-gac.github.io/SISG_2021/ancestry-and-relatedness-inference.html)) ([Exercises](https://uw-gac.github.io/SISG_2021/ancestry-and-relatedness-inference.html#exercises-1)) ([Solutions](https://uw-gac.github.io/SISG_2021/ancestry-and-relatedness-inference.html#solutions-1))
        - Discussion ([video]())

**Friday, July 23**

- **Zoom session 8:00-9:30 PDT** - Mixed models
    - **Lecture**
        - Mixed model association testing ([pre-recorded video - 42 min](https://drive.google.com/file/d/1H01K3rhjsKiFCmIcXRRkPxoGF_a6DojL/view?usp=sharing)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/Mixed_Model_Association_Testing_2020.pdf))
    - **Interactive breakout rooms**
        - Mixed models in R ([Demo](https://uw-gac.github.io/SISG_2021/mixed-models.html)) ([Exercise](https://uw-gac.github.io/SISG_2021/mixed-models.html#exercise-3)) ([Solution](https://uw-gac.github.io/SISG_2021/mixed-models.html#solution-3))
        - Discussion ([video]())
        
- **Zoom session 9:45-11:30 PDT** - Variant annotation
    - **Lecture**
        - Variant annotation ([pre-recorded video - 21 min](https://washington.zoom.us/rec/share/5cpzcuntpklJW8_K7mKPZ7U4RY7-T6a81CZLqfcLmEZ4UtOvefz1dn05i3eFNAjJ?startTime=1595707556000)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/variant_annotation_0.pdf))
    - **Interactive breakout rooms**
        - Using variant annotation ([Demo](https://uw-gac.github.io/SISG_2021/variant-annotation.html)) ([Exercise]()) ([Solution]())
        - Discussion ([video]()) - includes 30 min of open questions and discussion
        
- **Zoom session 12:30-13:45 PDT** - Working in the cloud
    - **Lecture**
        - Analysis pipelines on the cloud  ([pre-recorded video - 24 min](https://washington.zoom.us/rec/share/4_1bI-3Q3UVLXJH07BmGSvUgTrz1eaa8hiceqPoPzUzd-fBH94rKeazO2iV8z6i6?startTime=1595875794000)) ([slides](https://si.biostat.washington.edu/sites/default/files/modules/Cloud_Computing.pdf))
        - Running a workflow on BioData Catalyst ([pre-recorded video - 16 min](https://washington.zoom.us/rec/share/wtxcFZPgzF5LTZXHxVPiQ5weMtreX6a81SNMrPIEn0sVFKctNRBSuHnZR4Lx78Bg?startTime=1595882071000))
    - **Interactive breakout rooms**
        - Running a GWAS workflow ([Demo](https://uw-gac.github.io/SISG_2021/exercises-running-a-gwas-workflow.html)) ([Exercise]()) ([Solution]())
        - Discussion ([video]())
        
- **Zoom session 14:00-14:30 PDT** - Open session for questions/advice
    - Discussion ([video]())



Download the workshop data and exercises: https://github.com/UW-GAC/SISG_2021/archive/master.zip

## R packages used

- [SeqArray](http://bioconductor.org/packages/release/bioc/html/SeqArray.html)
- [SeqVarTools](http://bioconductor.org/packages/release/bioc/html/SeqVarTools.html)
- [GENESIS](http://bioconductor.org/packages/release/bioc/html/GENESIS.html)
- [SNPRelate](http://bioconductor.org/packages/release/bioc/html/SNPRelate.html)
- [TopmedPipeline](https://github.com/UW-GAC/analysis_pipeline/tree/master/TopmedPipeline)
- [tidyverse](https://www.tidyverse.org)
- [GGally](https://cran.r-project.org/web/packages/GGally)


## Resources

If you are new to R, you might find the following material helpful:

- [Introduction to R](http://faculty.washington.edu/kenrice/rintro/indexSEA15.shtml) materials from SISG Module 3
- [Graphics with ggplot2](http://tutorials.iq.harvard.edu/R/Rgraphics/Rgraphics.html) tutorial
- Data manipulation with [dplyr](http://dplyr.tidyverse.org/)
